#theme: jekyll-theme-midnight
#remote_theme: TaylanTatli/Moon
#remote_theme: pranavrajs/limpid
title: Comunidad Som Labs
logo: logo-hackasom2017.jpg
show_downloads: true
lang: es
#google_analytics: [Your Google Analytics tracking ID]
