#theme: jekyll-theme-midnight
#remote_theme: TaylanTatli/Moon
#remote_theme: pranavrajs/limpid
title: Som Labs Community
logo: hackasom2018.png
show_downloads: false
#google_analytics: [Your Google Analytics tracking ID]
